# Generated by Django 5.1.7 on 2025-03-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrealtimedata',
            name='high_price',
        ),
    ]
