# Generated by Django 5.1.7 on 2025-03-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0003_stockhistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockhistory',
            table='江西铜业_history',
        ),
    ]
