# Generated by Django 5.1.7 on 2025-03-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0004_alter_stockhistory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistorydata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='stockhistory',
            table='your_table_name',
        ),
    ]
