# Generated by Django 5.1.7 on 2025-03-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0005_alter_stockhistorydata_id_alter_stockhistory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockhistory',
            table='东阿阿胶_history',
        ),
    ]
